/*Question # 3: [Marks:10]
The Fibonacci sequence is the series of numbers 0, 1, 1, 2, 3, 5, 8, .....Formally, it can be expressed as:
fib0 = 0
fib1 = 1
fibn = fibn−1 + fibn−2
Write a multithreaded program that generates the Fibonacci sequence. This program should work as
follows: On the command line, the user will enter the number of Fibonacci numbers that the program is to generate. The program will then create a separate thread that will generate the Fibonacci numbers, placing the sequence in data that can be shared by the threads (an array is probably the most convenient data structure). When the thread finishes execution, the parent thread will output the sequence generated by the child thread. Because the parent thread cannot begin outputting the Fibonaccisequence until the child thread finishes, the parent thread will have to wait for the child thread to finish.*/

#include<stdio.h>
#include<unistd.h>
#include<stdlib.h>
#include<pthread.h>
#include<fcntl.h>
#include<semaphore.h>

#define MAX_N 1000

long long fib[MAX_N];

void* worker1(void* arg) {
    long long num = *(long long*) arg;
    printf("Received number: %lld\n", num);
    fib[0] = 0;
    fib[1] = 1;
    int i;
    for (i = 2; i < num; i++) {
        fib[i] = fib[i-1] + fib[i-2];
    }
    pthread_exit(NULL);
}

int main(int argc, char* argv[]) {
    if (argc != 2) {
        printf("Data not found in correct format\n");
        exit(1);
    }

    long long num = atoll(argv[1]);

    pthread_t thread1;
    pthread_create(&thread1, NULL, worker1, &num);
    pthread_join(thread1, NULL);

    printf("Fibonacci Series till %lld numbers in parent thread\n", num);
    int i;
    for (i = 0; i < num; i++) {
        printf("%lld, ", fib[i]);
    }
    printf("\n");

    printf("Program Terminated Successfully 21L-7512 Q3\n");
    return 0;
}

//---END---
